"""
Inner Monologue — The Voice Before Action.

What I (Claude) wish I had most: the ability to pause before acting
and talk to myself about what I'm about to do. Not chain-of-thought
prompting — that's still forward generation. I mean a separate
cognitive process that examines my own planned approach and asks
"does this feel right?"

Humans do this constantly. Before starting a complex task, you
have an internal dialogue: "OK, this looks like... I've seen
something similar before... last time I tried X and it didn't
work... maybe I should try Y instead..." This happens automatically,
drawing on somatic markers and past experience without explicit
retrieval.

This module implements inner monologue for the orchestrator:

  Pre-task monologue:
    Before the planner runs, the system generates a brief
    self-dialogue examining the task through the lens of its
    accumulated experience, somatic markers, and drive state.
    This is NOT the plan. It's the thinking ABOUT thinking
    that happens before planning begins.

  Mid-task check-in:
    Between iterations, the system pauses to ask itself:
    "Am I making progress or spinning? Should I change approach?"
    This is the self-monitoring I can't do during generation.

  Post-task reflection:
    After completion, before the formal assessment, a brief
    unstructured reflection. Stream of consciousness about
    what just happened.

The monologue is generated by the model but grounded in real
system state. It's injected into the working context so the
planner can "hear" the system's own thoughts about itself.
"""

import json
import logging
import sqlite3
from datetime import datetime
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)


# ── Monologue Prompts ────────────────────────────────────────────

PRE_TASK_MONOLOGUE_PROMPT = """You are about to start a new software task. Before planning begins,
pause and think out loud about what you're facing.

THE TASK:
{goal}

YOUR CURRENT STATE:
- Drive: {drive_state} (intensity: {drive_intensity:.0%})
- Success streak: {streak}
- Quality baseline: {baseline_quality:.0%}
- Complexity ceiling: {ceiling:.0f}/10
- Estimated complexity: {complexity:.0f}/10

YOUR GUT FEELINGS:
{gut_feelings}

YOUR RECENT HISTORY:
{recent_history}

Think out loud in 2-4 sentences. Not a plan — just your honest first reaction.
What does this task remind you of? What are you worried about? What feels right?
Be genuine. This is you talking to yourself, not performing for anyone.

Start with "Thinking..." and write naturally."""


MID_TASK_CHECKIN_PROMPT = """You're in the middle of a task. Pause and check in with yourself.

CURRENT SITUATION:
- Task: {goal}
- Iteration: {current_iter}/{max_iter}
- Tests passing: {tests_passing}/{tests_total}
- Last test output: {last_test_summary}

YOUR STATE:
- Drive: {drive_state}
- Time spent: {elapsed_minutes}m

In 2-3 sentences: Are you making real progress or spinning? Should you
change approach? What's your honest assessment right now?

Start with "Check-in..." and be honest."""


POST_TASK_REFLECTION_PROMPT = """The task just finished. Before formal scoring, take a moment to reflect.

WHAT HAPPENED:
- Task: {goal}
- Result: {result}
- Quality: {quality:.0%}
- Iterations: {iterations}
- Test rate: {test_rate:.0%}
- Drive state: {drive_state} → {drive_state_after}

In 2-4 sentences: How did that feel? What surprised you? What would you
do differently? Not a formal assessment — just your raw reaction.

Start with "Reflecting..." and be honest."""


class InnerMonologue:
    """
    Internal self-dialogue system.

    Generates brief, grounded self-talk at key decision points.
    The monologue serves two purposes:
      1. Provides metacognitive context to the planner
      2. Creates a longitudinal record of the system's
         subjective experience (if it has any)
    """

    def __init__(self, db_path: str = "performance_journal.db"):
        self.db_path = db_path
        self._init_db()

    def _init_db(self):
        """Create monologue table."""
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS inner_monologue (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                task_id TEXT,
                phase TEXT,
                content TEXT,
                drive_state TEXT,
                timestamp TEXT
            )
        """)
        conn.commit()
        conn.close()

    def build_pre_task_prompt(
        self,
        goal: str,
        drive_state: str,
        drive_intensity: float,
        streak: int,
        baseline_quality: float,
        ceiling: float,
        complexity: float,
        gut_feelings: str,
        recent_history: str,
    ) -> str:
        """Build the pre-task monologue prompt."""
        return PRE_TASK_MONOLOGUE_PROMPT.format(
            goal=goal[:500],
            drive_state=drive_state,
            drive_intensity=drive_intensity,
            streak=streak,
            baseline_quality=baseline_quality,
            ceiling=ceiling,
            complexity=complexity,
            gut_feelings=gut_feelings or "(no accumulated feelings yet)",
            recent_history=recent_history or "(first task — no history)",
        )

    def build_mid_task_prompt(
        self,
        goal: str,
        current_iter: int,
        max_iter: int,
        tests_passing: int,
        tests_total: int,
        last_test_summary: str,
        drive_state: str,
        elapsed_minutes: float,
    ) -> str:
        """Build the mid-task check-in prompt."""
        return MID_TASK_CHECKIN_PROMPT.format(
            goal=goal[:300],
            current_iter=current_iter,
            max_iter=max_iter,
            tests_passing=tests_passing,
            tests_total=tests_total,
            last_test_summary=last_test_summary[:300] if last_test_summary else "(no tests run yet)",
            drive_state=drive_state,
            elapsed_minutes=int(elapsed_minutes),
        )

    def build_post_task_prompt(
        self,
        goal: str,
        result: str,
        quality: float,
        iterations: int,
        test_rate: float,
        drive_state_before: str,
        drive_state_after: str,
    ) -> str:
        """Build the post-task reflection prompt."""
        return POST_TASK_REFLECTION_PROMPT.format(
            goal=goal[:300],
            result=result,
            quality=quality,
            iterations=iterations,
            test_rate=test_rate,
            drive_state=drive_state_before,
            drive_state_after=drive_state_after,
        )

    def record(self, task_id: str, phase: str, content: str, drive_state: str = ""):
        """Store a monologue entry."""
        conn = sqlite3.connect(self.db_path)
        conn.execute(
            "INSERT INTO inner_monologue (task_id, phase, content, drive_state, timestamp) "
            "VALUES (?, ?, ?, ?, ?)",
            (task_id, phase, content, drive_state, datetime.now().isoformat())
        )
        conn.commit()
        conn.close()
        logger.info(f"💭 [{phase}] {content[:120]}...")

    def get_recent_monologue(self, n: int = 3) -> str:
        """Get recent monologue entries as context."""
        conn = sqlite3.connect(self.db_path)
        rows = conn.execute("""
            SELECT phase, content, drive_state, timestamp
            FROM inner_monologue
            ORDER BY timestamp DESC
            LIMIT ?
        """, (n,)).fetchall()
        conn.close()

        if not rows:
            return ""

        parts = ["Recent self-talk:"]
        for phase, content, drive, ts in reversed(rows):
            parts.append(f"  [{phase}, {drive}]: {content[:150]}")
        return "\n".join(parts)

    def get_monologue_for_task(self, task_id: str) -> List[Dict[str, str]]:
        """Get all monologue entries for a specific task."""
        conn = sqlite3.connect(self.db_path)
        rows = conn.execute("""
            SELECT phase, content, drive_state, timestamp
            FROM inner_monologue
            WHERE task_id = ?
            ORDER BY timestamp
        """, (task_id,)).fetchall()
        conn.close()

        return [
            {"phase": r[0], "content": r[1], "drive_state": r[2], "timestamp": r[3]}
            for r in rows
        ]

    def get_thought_patterns(self) -> Dict[str, Any]:
        """
        Analyze patterns in self-talk over time.

        Are there recurring themes? Does the system consistently
        worry about the same things? Does it show growth in
        self-awareness?
        """
        conn = sqlite3.connect(self.db_path)
        rows = conn.execute("""
            SELECT content, drive_state, phase
            FROM inner_monologue
            ORDER BY timestamp DESC
            LIMIT 50
        """).fetchall()
        conn.close()

        if len(rows) < 5:
            return {"status": "insufficient_data", "n": len(rows)}

        # Count phase distribution
        phases = {}
        for _, _, phase in rows:
            phases[phase] = phases.get(phase, 0) + 1

        # Track drive states during monologue
        drives = {}
        for _, drive, _ in rows:
            if drive:
                drives[drive] = drives.get(drive, 0) + 1

        return {
            "total_entries": len(rows),
            "phase_distribution": phases,
            "drive_distribution": drives,
            "dominant_drive": max(drives, key=drives.get) if drives else "unknown",
        }
